config/routes.rb
Rails.application.routes.draw do
  get '/app' => 'pages#app', as: 'app'

  # Rails login_path
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # ajax routes:

  # Posts
  get '/latest' => 'posts#latest'
  get '/posts/:id' => 'posts#show'
  post '/posts' => 'posts#create'
  post '/posts/:id' => 'posts#update'


  # Users
  resources :users, except: [:index, :show]
  get '/users' => 'users#index'
  get '/users/:id' => 'users#show'
  post '/users/:id' => 'users#update'

  # get '/users/:id' => 'users#new'
  # post '/users/:id' => 'users#create'
  # delete '/users/:id' => 'users#destroy'

  # resources :users
  # resources :posts
  # get "/posts/:id/add" => "posts#add_post", as: "add_post"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :post, optional: true
belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments
  has_and_belongs_to_many :fans, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  has_many :comments
  has_and_belongs_to_many :liked_posts, class_name: 'Post'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Our fetch_user method will be run before ANY action of ANY controller
    # (because ApplicationController is the parent class of all of them)
    before_action :fetch_user

    private

    def check_if_logged_in
      unless @current_user.present?
        flash[:error] = "You must be logged in to view that page."
        redirect_to login_path

      end
    end

    def fetch_user
      # Check if session[:user_id] is set, and also if it stores
      # a valid user ID, and if so, set an instance variable
      # containing the user object

      if session[:user_id].present?
        @current_user = User.find_by id: session[:user_id]
      end

      # Make sure we actually found a valid user (i.e. the user ID in
      # the session wasn't stale, from a deleted account)
      # and if we didn't get a valid user (in @current_user)
      # then we clear the session key
      session[:user_id] = nil unless @current_user.present?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def app
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  before_action :check_if_logged_in

  skip_before_action :verify_authenticity_token

  def latest
    render json: Post.all.reverse_order.limit(10)
  end

  def show
    render(json: Post.find(params[:id]), include: {
      comments: {
        include: {
          user: {
            only: [:name, :image]
          }
        }
      }
    })
  end

  def create
    post = Post.create(
      heading: params[:heading],
      content: params[:content],
      image: params[:image],
      user: @current_user
    )

    if post.persisted?
      render json: post
    else
      render json: {errors: post.errors.full_messages}
    end

  end # create

  def update
    post = Post.find(params[:id])
    post.update(
      heading: params[:heading],
      content: params[:content],
      image: params[:image],
    )

    # TODO: error handling in case of validation error, etc!
    render json: post

  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    redirect_to app_path if @current_user.present?
  end

  def create
    # see if the email address entered actually corresponds to a user in the table
    user = User.find_by email: params[:email]

    if user.present? && user.authenticate( params[:password] )
      # Successful login:
      # Get Rails to create a new session key to store the user's ID;
      # this is the session key which we will use to check if the user
      # is logged in on all future pages
      session[:user_id] = user.id
      redirect_to app_path #user_path( user.id )
    else
      # Bad credentials, i.e. unsuccessful login

      # Set a flash message which exists *just for the next page load*
      flash[:error] = "Invalid email address or password"

      redirect_to( login_path )
    end

  end

  def destroy
    session[:user_id] = nil  # this logs out the user
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :check_if_logged_in
  def new
    @user = User.new
  end

  def create
    user = User.new user_params   # strong params
    # render json: User.new( params[:id] )
    # upload image if given
    if params[:file].present?
      response = Cloudinary::Uploader.upload(params[:file])
      user.image = response["public_id"]
    end

    user.save  # persist the user object to the database

    if user.persisted?
      # Account created successfully!
      session[:user_id] = user.id   # Log in the new user!!
      redirect_to user_path(user)   # go to the show page for this user
    else
      # Account not created: show error

      # Set a flash key to show on the next page: it will be an array of error strings
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path  # /users/new, show the form again (with errors)
    end


  end

  def show
    # @user = User.find params[:id]
      render json: User.find( params[:id] )
   end

  def edit
@user = User.find params[:id]
  end


  def index
    render json: User.all
  end

  def update


  end

  def destroy
    user = User.find params[:id]  # key comes from /mixtapes/:id
    user.destroy
    redirect_to users_path
  end

  private
  # strong params, the doorman for the form fields
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AngularWebpackerApp</title>
      <!-- <base href="/app"> -->
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_pack_tag    'application' %>
    <%= javascript_pack_tag    'application' %>
  </head>
  <body>
    <nav>
    <ul>
      <span class="site-enter">
        <% if @current_user.present? %>
         <li>
           Welcome, <%= @current_user.name %>
         </li>
          <li>
            <%= link_to 'Logout', login_path, method: 'delete', class: "nav-items" %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Login', login_path, class: "nav-items" %>
          </li>
          <li>
            <%= link_to 'Sign up', new_user_path, class: "nav-items" %>
          </li>
        <% end %>

        <li>
            <a href="/app#/users">All Users</a>
        </li>
      </span>

      <span class="site-navigation">
        <li><a href="/app#/posts/new">New Post</a></li>
        <li><a href="/app#/posts/15/edit">Edit Post</a></li>
        <li><a href="/app#/posts/">Posts</a></li>
        <li><a href="/app#/users">User Profile</a></li>
        <li><a href="/app#/7/users">Edit User</a></li>
      </span>
    </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/app.html.erb
<br>
<br>

<hello-angular> </hello-angular>

<%= javascript_pack_tag 'hello_angular' %>

app/views/session/new.html.erb
<% if flash[:error] %>
  <br>
  <strong><%= flash[:error] %></strong>
  <br><br>
<% end %>

<div class="login-box">

  <div class="login-contents">

    <div class="form-group">
      <%= form_tag login_path do %>
        <%= label_tag :email %>
        <%=  email_field_tag :email, nil, class: "form-control" %>
        <br>

        <%= label_tag :password %>
        <%= password_field_tag :password, nil, class: "form-control" %>
        <br>
        <%= submit_tag 'Login', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<h2>All Users (debugging)</h2>

<ul>
<% @users.each do |user| %>
   <li>
     <%= link_to user.name, user_path(user.id) %>
   </li>
<% end %>
</ul>

app/views/users/new.html.erb
<h2>Create an Account</h2>

<% if flash[:errors].present?  %>
   <strong>Please correct the following errors:</strong>
   <ol>
   <% flash[:errors].each do |error| %>
     <li><%= error %></li>
   <% end %>
   </ol>
<% end %>

<%= form_for @user, html: {multipart:true} do |f| %>

  <%= f.label :name, class:"signup-items"%>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email, class: "signup-items" %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password, class: "signup-items" %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation, class: "signup-items" %>
  <%= f.password_field :password_confirmation %>
  <br>



  <br>

  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<div class="container-fluid">
  <div class="row">

    <div class="col-4">
      1st of three columns

      <!-- If the logged-in user is looking at their own profile -->
      <% if @current_user.present? && @user == @current_user %>
        <%= link_to 'Edit User', edit_user_path(@user)  %>
      |
        <%= link_to 'Delete User', user_path(@user), method: 'delete' %>
      <% end %>

      <br>

  <%= cl_image_tag @user.image, class: 'profilepic' %>
<br>
<%= @user.name%>




    </div><!-- end of 1st col -->

    <div class="col-4">
    2nd of three columns

<!-- Show list of all posts made by this user, with links to the show page for each post -->
<ul>
<% @user.posts.each do |post| %>
  <li>
    <%= link_to post.heading, post_path(post.id) %>
  </li>
<% end %>
</ul>

</div><!-- end of 2nd col -->

    <div class="col-4">
      3rd of three columns

      <ul>
      <% @user.liked_posts.each do |post| %>
        <li>
          <%= link_to post.heading, post_path(post.id) %>
        </li>
      <% end %>
      </ul>


    </div><!-- end of 3rd col -->